/*
 * FILE : uri_wrap.c
 * 
 * This file was automatically generated by :
 * Simplified Wrapper and Interface Generator (SWIG)
 * Version 1.1 (Patch 5)
 * 
 * Portions Copyright (c) 1995-1998
 * The University of Utah and The Regents of the University of California.
 * Permission is granted to distribute this file in any manner provided
 * this notice remains intact.
 * 
 * Do not make changes to this file--changes will be lost!
 *
 */


#define SWIGCODE
/* Implementation : PERL 5 */

#define SWIGPERL
#define SWIGPERL5
#ifdef __cplusplus
#include <math.h>
#include <stdlib.h>
extern "C" {
#endif
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#undef free
#undef malloc
#include <string.h>
#ifdef __cplusplus
}
#endif
/* Definitions for compiling Perl extensions on a variety of machines */

#if defined(WIN32) || defined(__WIN32__)
#   if defined(_MSC_VER)
#	define SWIGEXPORT(a,b) __declspec(dllexport) a b
#   else
#	if defined(__BORLANDC__)
#	    define SWIGEXPORT(a,b) a _export b
#	else
#	    define SWIGEXPORT(a,b) a b
#	endif
#   endif
#else
#   define SWIGEXPORT(a,b) a b
#endif

#ifdef PERL_OBJECT
#define MAGIC_PPERL  CPerl *pPerl = (CPerl *) this;
#define MAGIC_CAST   (int (CPerl::*)(SV *, MAGIC *))
#define SWIGCLASS_STATIC 
#else
#define MAGIC_PPERL
#define MAGIC_CAST
#define SWIGCLASS_STATIC static
#endif


/*****************************************************************************
 * $Header: /home/beazley/SWIG/SWIG1.1b3/swig_lib/perl5/RCS/perl5ptr.swg,v 1.1 1996/12/26 22:17:29 beazley Exp beazley $
 *
 * perl5ptr.swg
 *
 * This file contains supporting code for the SWIG run-time type checking
 * mechanism.  The following functions are available :
 *
 * SWIG_RegisterMapping(char *origtype, char *newtype, void *(*cast)(void *));
 *
 *      Registers a new type-mapping with the type-checker.  origtype is the
 *      original datatype and newtype is an equivalent type.  cast is optional
 *      pointer to a function to cast pointer values between types (this
 *      is only used to cast pointers from derived classes to base classes in C++)
 *      
 * SWIG_MakePtr(char *buffer, void *ptr, char *typestring);
 *     
 *      Makes a pointer string from a pointer and typestring.  The result is returned
 *      in buffer.
 *
 * char * SWIG_GetPtr(SV *obj, void **ptr, char *type)
 *
 *      Gets a pointer value from a Perl5 scalar value.  If there is a 
 *      type-mismatch, returns a character string to the received type.  
 *      On success, returns NULL.
 *
 *
 * You can remap these functions by making a file called "swigptr.swg" in
 * your the same directory as the interface file you are wrapping.
 *
 * These functions are normally declared static, but this file can be
 * can be used in a multi-module environment by redefining the symbol
 * SWIGSTATIC.
 *
 * $Log: perl5ptr.swg,v $
 * Revision 1.1  1996/12/26 22:17:29  beazley
 * Initial revision
 *
 *****************************************************************************/

#include <stdlib.h>

#ifdef SWIG_GLOBAL
#ifdef __cplusplus
#define SWIGSTATIC extern "C"
#else
#define SWIGSTATIC
#endif
#endif

#ifndef SWIGSTATIC
#define SWIGSTATIC static
#endif

/* These are internal variables.   Should be static */

typedef struct SwigPtrType {
  char               *name;
  int                 len;
  void               *(*cast)(void *);
  struct SwigPtrType *next;
} SwigPtrType;

/* Pointer cache structure */

typedef struct {
  int                 stat;               /* Status (valid) bit             */
  SwigPtrType        *tp;                 /* Pointer to type structure      */
  char                name[256];          /* Given datatype name            */
  char                mapped[256];        /* Equivalent name                */
} SwigCacheType;

static int SwigPtrMax  = 64;           /* Max entries that can be currently held */
static int SwigPtrN    = 0;            /* Current number of entries              */
static int SwigPtrSort = 0;            /* Status flag indicating sort            */
static SwigPtrType *SwigPtrTable = 0;  /* Table containing pointer equivalences  */
static int SwigStart[256];             /* Table containing starting positions    */

/* Cached values */

#define SWIG_CACHESIZE  8
#define SWIG_CACHEMASK  0x7
static SwigCacheType SwigCache[SWIG_CACHESIZE];  
static int SwigCacheIndex = 0;
static int SwigLastCache = 0;

/* Sort comparison function */
static int swigsort(const void *data1, const void *data2) {
	SwigPtrType *d1 = (SwigPtrType *) data1;
	SwigPtrType *d2 = (SwigPtrType *) data2;
	return strcmp(d1->name,d2->name);
}

/* Binary Search function */
static int swigcmp(const void *key, const void *data) {
  char *k = (char *) key;
  SwigPtrType *d = (SwigPtrType *) data;
  return strncmp(k,d->name,d->len);
}

/* Register a new datatype with the type-checker */

#ifndef PERL_OBJECT
SWIGSTATIC 
void SWIG_RegisterMapping(char *origtype, char *newtype, void *(*cast)(void *)) {
#else
SWIGSTATIC
#define SWIG_RegisterMapping(a,b,c) _SWIG_RegisterMapping(pPerl, a,b,c)
void _SWIG_RegisterMapping(CPerl *pPerl, char *origtype, char *newtype, void *(*cast)(void *)) {
#endif

  int i;
  SwigPtrType *t = 0, *t1;

  if (!SwigPtrTable) {     
    SwigPtrTable = (SwigPtrType *) malloc(SwigPtrMax*sizeof(SwigPtrType));
    SwigPtrN = 0;
  }
  if (SwigPtrN >= SwigPtrMax) {
    SwigPtrMax = 2*SwigPtrMax;
    SwigPtrTable = (SwigPtrType *) realloc(SwigPtrTable,SwigPtrMax*sizeof(SwigPtrType));
  }
  for (i = 0; i < SwigPtrN; i++)
    if (strcmp(SwigPtrTable[i].name,origtype) == 0) {
      t = &SwigPtrTable[i];
      break;
    }
  if (!t) {
    t = &SwigPtrTable[SwigPtrN];
    t->name = origtype;
    t->len = strlen(t->name);
    t->cast = 0;
    t->next = 0;
    SwigPtrN++;
  }
  while (t->next) {
    if (strcmp(t->name,newtype) == 0) {
      if (cast) t->cast = cast;
      return;
    }
    t = t->next;
  }
  t1 = (SwigPtrType *) malloc(sizeof(SwigPtrType));
  t1->name = newtype;
  t1->len = strlen(t1->name);
  t1->cast = cast;
  t1->next = 0;
  t->next = t1;
  SwigPtrSort = 0;
}

/* Make a pointer value string */

SWIGSTATIC 
void SWIG_MakePtr(char *_c, const void *_ptr, char *type) {
  static char _hex[16] =
  {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
   'a', 'b', 'c', 'd', 'e', 'f'};
  unsigned long _p, _s;
  char _result[20], *_r;    /* Note : a 64-bit hex number = 16 digits */
  _r = _result;
  _p = (unsigned long) _ptr;
  if (_p > 0) {
    while (_p > 0) {
      _s = _p & 0xf;
      *(_r++) = _hex[_s];
      _p = _p >> 4;
    }
    *_r = '_';
    while (_r >= _result)
      *(_c++) = *(_r--);
  } else {
    strcpy (_c, "NULL");
  }
  if (_ptr)
    strcpy (_c, type);
}

/* Define for backwards compatibility */

#define _swig_make_hex   SWIG_MakePtr 

/* Function for getting a pointer value */

#ifndef PERL_OBJECT
SWIGSTATIC 
char *SWIG_GetPtr(SV *sv, void **ptr, char *_t)
#else
SWIGSTATIC
#define SWIG_GetPtr(a,b,c) _SWIG_GetPtr(pPerl,a,b,c)
char *_SWIG_GetPtr(CPerl *pPerl, SV *sv, void **ptr, char *_t)
#endif
{
  char temp_type[256];
  char *name,*_c;
  int  len,i,start,end;
  IV   tmp;
  SwigPtrType *sp,*tp;
  SwigCacheType *cache;

  /* If magical, apply more magic */

  if (SvGMAGICAL(sv))
    mg_get(sv);

  /* Check to see if this is an object */
  if (sv_isobject(sv)) {
    SV *tsv = (SV*) SvRV(sv);
    if ((SvTYPE(tsv) == SVt_PVHV)) {
      MAGIC *mg;
      if (SvMAGICAL(tsv)) {
	mg = mg_find(tsv,'P');
	if (mg) {
	  SV *rsv = mg->mg_obj;
	  if (sv_isobject(rsv)) {
	    tmp = SvIV((SV*)SvRV(rsv));
	  }
	}
      } else {
	return "Not a valid pointer value";
      }
    } else {
      tmp = SvIV((SV*)SvRV(sv));
    }
    if (!_t) {
      *(ptr) = (void *) tmp;
      return (char *) 0;
    }
  } else if (sv == &sv_undef) {            /* Check for undef */
    *(ptr) = (void *) 0;
    return (char *) 0;
  } else if (SvTYPE(sv) == SVt_RV) {       /* Check for NULL pointer */
    *(ptr) = (void *) 0;
    if (!SvROK(sv)) 
      return (char *) 0;
    else
      return "Not a valid pointer value";
  } else {                                 /* Don't know what it is */
      *(ptr) = (void *) 0;
      return "Not a valid pointer value";
  }
  if (_t) {
    /* Now see if the types match */      

    if (!sv_isa(sv,_t)) {
      _c = HvNAME(SvSTASH(SvRV(sv)));
      if (!SwigPtrSort) {
	qsort((void *) SwigPtrTable, SwigPtrN, sizeof(SwigPtrType), swigsort);  
	for (i = 0; i < 256; i++) {
	  SwigStart[i] = SwigPtrN;
	}
	for (i = SwigPtrN-1; i >= 0; i--) {
	  SwigStart[SwigPtrTable[i].name[0]] = i;
	}
	for (i = 255; i >= 1; i--) {
	  if (SwigStart[i-1] > SwigStart[i])
	    SwigStart[i-1] = SwigStart[i];
	}
	SwigPtrSort = 1;
	for (i = 0; i < SWIG_CACHESIZE; i++)  
	  SwigCache[i].stat = 0;
      }
      /* First check cache for matches.  Uses last cache value as starting point */
      cache = &SwigCache[SwigLastCache];
      for (i = 0; i < SWIG_CACHESIZE; i++) {
	if (cache->stat) {
	  if (strcmp(_t,cache->name) == 0) {
	    if (strcmp(_c,cache->mapped) == 0) {
	      cache->stat++;
	      *ptr = (void *) tmp;
	      if (cache->tp->cast) *ptr = (*(cache->tp->cast))(*ptr);
	      return (char *) 0;
	    }
	  }
	}
	SwigLastCache = (SwigLastCache+1) & SWIG_CACHEMASK;
	if (!SwigLastCache) cache = SwigCache;
	else cache++;
      }

      start = SwigStart[_t[0]];
      end = SwigStart[_t[0]+1];
      sp = &SwigPtrTable[start];
      while (start < end) {
	if (swigcmp(_t,sp) == 0) break;
	sp++;
	start++;
      }
      if (start >= end) sp = 0;
      if (sp) {
	while (swigcmp(_t,sp) == 0) {
	  name = sp->name;
	  len = sp->len;
	  tp = sp->next;
	  while(tp) {
	    if (tp->len >= 255) {
	      return _c;
	    }
	    strcpy(temp_type,tp->name);
	    strncat(temp_type,_t+len,255-tp->len);
	    if (sv_isa(sv,temp_type)) {
	      /* Get pointer value */
	      *ptr = (void *) tmp;
	      if (tp->cast) *ptr = (*(tp->cast))(*ptr);

	      strcpy(SwigCache[SwigCacheIndex].mapped,_c);
	      strcpy(SwigCache[SwigCacheIndex].name,_t);
	      SwigCache[SwigCacheIndex].stat = 1;
	      SwigCache[SwigCacheIndex].tp = tp;
	      SwigCacheIndex = SwigCacheIndex & SWIG_CACHEMASK;
	      return (char *) 0;
	    }
	    tp = tp->next;
	  } 
	  /* Hmmm. Didn't find it this time */
 	  sp++;
	}
      }
      /* Didn't find any sort of match for this data.  
	 Get the pointer value and return the received type */
      *ptr = (void *) tmp;
      return _c;
    } else {
      /* Found a match on the first try.  Return pointer value */
      *ptr = (void *) tmp;
      return (char *) 0;
    }
  } 
  *ptr = (void *) tmp;
  return (char *) 0;
}

/* Compatibility mode */

#define _swig_get_hex  SWIG_GetPtr
/* Magic variable code */
#ifndef PERL_OBJECT
#define swig_create_magic(s,a,b,c) _swig_create_magic(s,a,b,c)
static void _swig_create_magic(SV *sv, char *name, int (*set)(SV *, MAGIC *), int (*get)(SV *,MAGIC *)) {
#else
#define swig_create_magic(s,a,b,c) _swig_create_magic(pPerl,s,a,b,c)
static void _swig_create_magic(CPerl *pPerl, SV *sv, char *name, int (CPerl::*set)(SV *, MAGIC *), int (CPerl::*get)(SV *, MAGIC *)) {
#endif
  MAGIC *mg;
  sv_magic(sv,sv,'U',name,strlen(name));
  mg = mg_find(sv,'U');
  mg->mg_virtual = (MGVTBL *) malloc(sizeof(MGVTBL));
  mg->mg_virtual->svt_get = get;
  mg->mg_virtual->svt_set = set;
  mg->mg_virtual->svt_len = 0;
  mg->mg_virtual->svt_clear = 0;
  mg->mg_virtual->svt_free = 0;
}

#define SWIG_init    boot_uri

#define SWIG_name   "uric::boot_uri"
#define SWIG_varinit "uric::var_uri_init();"
#ifdef __cplusplus
extern "C"
#endif
#ifndef PERL_OBJECT
SWIGEXPORT(void,boot_uri)(CV* cv);
#else
SWIGEXPORT(void,boot_uri)(CPerl *, CV *cv);
#endif

#include "urilib/uri.h"
#ifndef PERL_OBJECT
#define swig_setiv(a,b) _swig_setiv(a,b)
static void _swig_setiv(char *name, long value) { 
#else
#define swig_setiv(a,b) _swig_setiv(pPerl,a,b)
static void _swig_setiv(CPerl *pPerl, char *name, long value) { 
#endif
     SV *sv; 
     sv = perl_get_sv(name,TRUE | 0x2);
     sv_setiv(sv, (IV) value);
     SvREADONLY_on(sv);
}

extern char * uri_errstr; 
#ifdef PERL_OBJECT
#define MAGIC_CLASS _wrap_uri_var::
class _wrap_uri_var : public CPerl {
public:
#else
#define MAGIC_CLASS
#endif
SWIGCLASS_STATIC int swig_magic_readonly(SV *sv, MAGIC *mg) {
    MAGIC_PPERL
    sv = sv; mg = mg;
    croak("Value is read-only.");
    return 0;
}
SWIGCLASS_STATIC int _wrap_set_uri_errstr(SV* sv, MAGIC *mg) {

    char *_a;

    MAGIC_PPERL
    mg = mg;
    _a = (char *) SvPV(sv,na);
    if (uri_errstr) free(uri_errstr);
    uri_errstr = (char *) malloc(strlen(_a)+1);
strcpy(uri_errstr,_a);
    return 1;
}

SWIGCLASS_STATIC int _wrap_val_uri_errstr(SV *sv, MAGIC *mg) {


    MAGIC_PPERL
    mg = mg;
    sv_setpv((SV*) sv, uri_errstr);
    return 1;
}



#ifdef PERL_OBJECT
};
#endif

XS(_wrap_uri_mode) {

    int  _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: uri_mode(flag);");
    _arg0 = (int )SvIV(ST(0));
    uri_mode(_arg0);
    XSRETURN(argvi);
}

XS(_wrap_uri_modep) {

    int  _result;
    int  _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: uri_modep(flag);");
    _arg0 = (int )SvIV(ST(0));
    _result = (int )uri_modep(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_uri_alloc) {

    uri_t * _result;
    char * _arg0;
    int  _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: uri_alloc(uri,uri_length);");
    _arg0 = (char *) SvPV(ST(0),na);
    _arg1 = (int )SvIV(ST(1));
    _result = (uri_t *)uri_alloc(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setref_pv(ST(argvi++),"uri_t", (void *) _result);
    XSRETURN(argvi);
}

XS(_wrap_uri_realloc) {

    int  _result;
    uri_t * _arg0;
    char * _arg1;
    int  _arg2;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 3) || (items > 3)) 
        croak("Usage: uri_realloc(object,uri,uri_length);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_realloc. Expected uri_t.");
        XSRETURN(1);
    }
    _arg1 = (char *) SvPV(ST(1),na);
    _arg2 = (int )SvIV(ST(2));
    _result = (int )uri_realloc(_arg0,_arg1,_arg2);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_uri_free) {

    uri_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: uri_free(object);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_free. Expected uri_t.");
        XSRETURN(1);
    }
    uri_free(_arg0);
    XSRETURN(argvi);
}

XS(_wrap_uri_abs) {

    uri_t * _result;
    uri_t * _arg0;
    char * _arg1;
    int  _arg2;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 3) || (items > 3)) 
        croak("Usage: uri_abs(base,relative_string,relative_length);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_abs. Expected uri_t.");
        XSRETURN(1);
    }
    _arg1 = (char *) SvPV(ST(1),na);
    _arg2 = (int )SvIV(ST(2));
    _result = (uri_t *)uri_abs(_arg0,_arg1,_arg2);
    ST(argvi) = sv_newmortal();
    sv_setref_pv(ST(argvi++),"uri_t", (void *) _result);
    XSRETURN(argvi);
}

XS(_wrap_uri_abs_1) {

    uri_t * _result;
    uri_t * _arg0;
    uri_t * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: uri_abs_1(base,relative);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_abs_1. Expected uri_t.");
        XSRETURN(1);
    }
    if (SWIG_GetPtr(ST(1),(void **) &_arg1,"uri_t")) {
        croak("Type error in argument 2 of uri_abs_1. Expected uri_t.");
        XSRETURN(1);
    }
    _result = (uri_t *)uri_abs_1(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setref_pv(ST(argvi++),"uri_t", (void *) _result);
    XSRETURN(argvi);
}

XS(_wrap_uri_port) {

    char * _result;
    uri_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: uri_port(object);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_port. Expected uri_t.");
        XSRETURN(1);
    }
    _result = (char *)uri_port(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

XS(_wrap_uri_netloc) {

    char * _result;
    uri_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: uri_netloc(object);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_netloc. Expected uri_t.");
        XSRETURN(1);
    }
    _result = (char *)uri_netloc(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

XS(_wrap_uri_auth) {

    char * _result;
    uri_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: uri_auth(object);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_auth. Expected uri_t.");
        XSRETURN(1);
    }
    _result = (char *)uri_auth(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

XS(_wrap_uri_all_path) {

    char * _result;
    uri_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: uri_all_path(object);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_all_path. Expected uri_t.");
        XSRETURN(1);
    }
    _result = (char *)uri_all_path(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

XS(_wrap_uri_copy) {

    uri_t * _arg0;
    uri_t * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: uri_copy(to,from);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_copy. Expected uri_t.");
        XSRETURN(1);
    }
    if (SWIG_GetPtr(ST(1),(void **) &_arg1,"uri_t")) {
        croak("Type error in argument 2 of uri_copy. Expected uri_t.");
        XSRETURN(1);
    }
    uri_copy(_arg0,_arg1);
    XSRETURN(argvi);
}

XS(_wrap_uri_dump) {

    uri_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: uri_dump(object);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_dump. Expected uri_t.");
        XSRETURN(1);
    }
    uri_dump(_arg0);
    XSRETURN(argvi);
}

XS(_wrap_uri_furi) {

    char * _result;
    uri_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: uri_furi(object);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_furi. Expected uri_t.");
        XSRETURN(1);
    }
    _result = (char *)uri_furi(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

XS(_wrap_uri_uri) {

    char * _result;
    uri_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: uri_uri(object);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_uri. Expected uri_t.");
        XSRETURN(1);
    }
    _result = (char *)uri_uri(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

XS(_wrap_uri_robots) {

    char * _result;
    uri_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: uri_robots(object);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_robots. Expected uri_t.");
        XSRETURN(1);
    }
    _result = (char *)uri_robots(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

XS(_wrap_uri2object) {

    uri_t * _result;
    char * _arg0;
    int  _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: uri2object(uri,uri_length);");
    _arg0 = (char *) SvPV(ST(0),na);
    _arg1 = (int )SvIV(ST(1));
    _result = (uri_t *)uri2object(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setref_pv(ST(argvi++),"uri_t", (void *) _result);
    XSRETURN(argvi);
}

XS(_wrap_uri_furi_string) {

    char * _result;
    char * _arg0;
    int  _arg1;
    int  _arg2;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 3) || (items > 3)) 
        croak("Usage: uri_furi_string(uri,uri_length,flag);");
    _arg0 = (char *) SvPV(ST(0),na);
    _arg1 = (int )SvIV(ST(1));
    _arg2 = (int )SvIV(ST(2));
    _result = (char *)uri_furi_string(_arg0,_arg1,_arg2);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

XS(_wrap_uri_cannonicalize_string) {

    char * _result;
    char * _arg0;
    int  _arg1;
    int  _arg2;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 3) || (items > 3)) 
        croak("Usage: uri_cannonicalize_string(uri,uri_length,flag);");
    _arg0 = (char *) SvPV(ST(0),na);
    _arg1 = (int )SvIV(ST(1));
    _arg2 = (int )SvIV(ST(2));
    _result = (char *)uri_cannonicalize_string(_arg0,_arg1,_arg2);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

XS(_wrap_uri_cannonicalize) {

    int  _result;
    uri_t * _arg0;
    int  _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: uri_cannonicalize(object,flag);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_cannonicalize. Expected uri_t.");
        XSRETURN(1);
    }
    _arg1 = (int )SvIV(ST(1));
    _result = (int )uri_cannonicalize(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_uri_parse) {

    int  _result;
    uri_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: uri_parse(object);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_parse. Expected uri_t.");
        XSRETURN(1);
    }
    _result = (int )uri_parse(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

#define uri_info_set(_swigobj,_swigval) (_swigobj->info = _swigval,_swigval)
XS(_wrap_uri_t_info_set) {

    int  _result;
    uri_t * _arg0;
    int  _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: uri_t_info_set(uri_t *,int );");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_info_set. Expected uri_t.");
        XSRETURN(1);
    }
    _arg1 = (int )SvIV(ST(1));
    _result = (int )uri_info_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

#define uri_info_get(_swigobj) ((int ) _swigobj->info)
XS(_wrap_uri_t_info_get) {

    int  _result;
    uri_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: uri_t_info_get(uri_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_info_get. Expected uri_t.");
        XSRETURN(1);
    }
    _result = (int )uri_info_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

static char * uri_scheme_set(uri_t *obj, char *val) {
    if (obj->scheme) free(obj->scheme);
    obj->scheme = (char *) malloc(strlen(val)+1);
    strcpy(obj->scheme,val);
    return val;
}
XS(_wrap_uri_t_scheme_set) {

    char * _result;
    uri_t * _arg0;
    char * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: uri_t_scheme_set(uri_t *,char *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_scheme_set. Expected uri_t.");
        XSRETURN(1);
    }
    _arg1 = (char *) SvPV(ST(1),na);
    _result = (char *)uri_scheme_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define uri_scheme_get(_swigobj) ((char *) _swigobj->scheme)
XS(_wrap_uri_t_scheme_get) {

    char * _result;
    uri_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: uri_t_scheme_get(uri_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_scheme_get. Expected uri_t.");
        XSRETURN(1);
    }
    _result = (char *)uri_scheme_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

static char * uri_host_set(uri_t *obj, char *val) {
    if (obj->host) free(obj->host);
    obj->host = (char *) malloc(strlen(val)+1);
    strcpy(obj->host,val);
    return val;
}
XS(_wrap_uri_t_host_set) {

    char * _result;
    uri_t * _arg0;
    char * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: uri_t_host_set(uri_t *,char *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_host_set. Expected uri_t.");
        XSRETURN(1);
    }
    _arg1 = (char *) SvPV(ST(1),na);
    _result = (char *)uri_host_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define uri_host_get(_swigobj) ((char *) _swigobj->host)
XS(_wrap_uri_t_host_get) {

    char * _result;
    uri_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: uri_t_host_get(uri_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_host_get. Expected uri_t.");
        XSRETURN(1);
    }
    _result = (char *)uri_host_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

static char * uri_port_set(uri_t *obj, char *val) {
    if (obj->port) free(obj->port);
    obj->port = (char *) malloc(strlen(val)+1);
    strcpy(obj->port,val);
    return val;
}
XS(_wrap_uri_t_port_set) {

    char * _result;
    uri_t * _arg0;
    char * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: uri_t_port_set(uri_t *,char *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_port_set. Expected uri_t.");
        XSRETURN(1);
    }
    _arg1 = (char *) SvPV(ST(1),na);
    _result = (char *)uri_port_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define uri_port_get(_swigobj) ((char *) _swigobj->port)
XS(_wrap_uri_t_port_get) {

    char * _result;
    uri_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: uri_t_port_get(uri_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_port_get. Expected uri_t.");
        XSRETURN(1);
    }
    _result = (char *)uri_port_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

static char * uri_path_set(uri_t *obj, char *val) {
    if (obj->path) free(obj->path);
    obj->path = (char *) malloc(strlen(val)+1);
    strcpy(obj->path,val);
    return val;
}
XS(_wrap_uri_t_path_set) {

    char * _result;
    uri_t * _arg0;
    char * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: uri_t_path_set(uri_t *,char *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_path_set. Expected uri_t.");
        XSRETURN(1);
    }
    _arg1 = (char *) SvPV(ST(1),na);
    _result = (char *)uri_path_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define uri_path_get(_swigobj) ((char *) _swigobj->path)
XS(_wrap_uri_t_path_get) {

    char * _result;
    uri_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: uri_t_path_get(uri_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_path_get. Expected uri_t.");
        XSRETURN(1);
    }
    _result = (char *)uri_path_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

static char * uri_params_set(uri_t *obj, char *val) {
    if (obj->params) free(obj->params);
    obj->params = (char *) malloc(strlen(val)+1);
    strcpy(obj->params,val);
    return val;
}
XS(_wrap_uri_t_params_set) {

    char * _result;
    uri_t * _arg0;
    char * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: uri_t_params_set(uri_t *,char *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_params_set. Expected uri_t.");
        XSRETURN(1);
    }
    _arg1 = (char *) SvPV(ST(1),na);
    _result = (char *)uri_params_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define uri_params_get(_swigobj) ((char *) _swigobj->params)
XS(_wrap_uri_t_params_get) {

    char * _result;
    uri_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: uri_t_params_get(uri_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_params_get. Expected uri_t.");
        XSRETURN(1);
    }
    _result = (char *)uri_params_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

static char * uri_query_set(uri_t *obj, char *val) {
    if (obj->query) free(obj->query);
    obj->query = (char *) malloc(strlen(val)+1);
    strcpy(obj->query,val);
    return val;
}
XS(_wrap_uri_t_query_set) {

    char * _result;
    uri_t * _arg0;
    char * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: uri_t_query_set(uri_t *,char *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_query_set. Expected uri_t.");
        XSRETURN(1);
    }
    _arg1 = (char *) SvPV(ST(1),na);
    _result = (char *)uri_query_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define uri_query_get(_swigobj) ((char *) _swigobj->query)
XS(_wrap_uri_t_query_get) {

    char * _result;
    uri_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: uri_t_query_get(uri_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_query_get. Expected uri_t.");
        XSRETURN(1);
    }
    _result = (char *)uri_query_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

static char * uri_frag_set(uri_t *obj, char *val) {
    if (obj->frag) free(obj->frag);
    obj->frag = (char *) malloc(strlen(val)+1);
    strcpy(obj->frag,val);
    return val;
}
XS(_wrap_uri_t_frag_set) {

    char * _result;
    uri_t * _arg0;
    char * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: uri_t_frag_set(uri_t *,char *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_frag_set. Expected uri_t.");
        XSRETURN(1);
    }
    _arg1 = (char *) SvPV(ST(1),na);
    _result = (char *)uri_frag_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define uri_frag_get(_swigobj) ((char *) _swigobj->frag)
XS(_wrap_uri_t_frag_get) {

    char * _result;
    uri_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: uri_t_frag_get(uri_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_frag_get. Expected uri_t.");
        XSRETURN(1);
    }
    _result = (char *)uri_frag_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

static char * uri_user_set(uri_t *obj, char *val) {
    if (obj->user) free(obj->user);
    obj->user = (char *) malloc(strlen(val)+1);
    strcpy(obj->user,val);
    return val;
}
XS(_wrap_uri_t_user_set) {

    char * _result;
    uri_t * _arg0;
    char * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: uri_t_user_set(uri_t *,char *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_user_set. Expected uri_t.");
        XSRETURN(1);
    }
    _arg1 = (char *) SvPV(ST(1),na);
    _result = (char *)uri_user_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define uri_user_get(_swigobj) ((char *) _swigobj->user)
XS(_wrap_uri_t_user_get) {

    char * _result;
    uri_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: uri_t_user_get(uri_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_user_get. Expected uri_t.");
        XSRETURN(1);
    }
    _result = (char *)uri_user_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

static char * uri_passwd_set(uri_t *obj, char *val) {
    if (obj->passwd) free(obj->passwd);
    obj->passwd = (char *) malloc(strlen(val)+1);
    strcpy(obj->passwd,val);
    return val;
}
XS(_wrap_uri_t_passwd_set) {

    char * _result;
    uri_t * _arg0;
    char * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: uri_t_passwd_set(uri_t *,char *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_passwd_set. Expected uri_t.");
        XSRETURN(1);
    }
    _arg1 = (char *) SvPV(ST(1),na);
    _result = (char *)uri_passwd_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define uri_passwd_get(_swigobj) ((char *) _swigobj->passwd)
XS(_wrap_uri_t_passwd_get) {

    char * _result;
    uri_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: uri_t_passwd_get(uri_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_passwd_get. Expected uri_t.");
        XSRETURN(1);
    }
    _result = (char *)uri_passwd_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

static char * uri_pool_set(uri_t *obj, char *val) {
    if (obj->pool) free(obj->pool);
    obj->pool = (char *) malloc(strlen(val)+1);
    strcpy(obj->pool,val);
    return val;
}
XS(_wrap_uri_t_pool_set) {

    char * _result;
    uri_t * _arg0;
    char * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: uri_t_pool_set(uri_t *,char *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_pool_set. Expected uri_t.");
        XSRETURN(1);
    }
    _arg1 = (char *) SvPV(ST(1),na);
    _result = (char *)uri_pool_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define uri_pool_get(_swigobj) ((char *) _swigobj->pool)
XS(_wrap_uri_t_pool_get) {

    char * _result;
    uri_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: uri_t_pool_get(uri_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_pool_get. Expected uri_t.");
        XSRETURN(1);
    }
    _result = (char *)uri_pool_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define uri_pool_size_set(_swigobj,_swigval) (_swigobj->pool_size = _swigval,_swigval)
XS(_wrap_uri_t_pool_size_set) {

    int  _result;
    uri_t * _arg0;
    int  _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: uri_t_pool_size_set(uri_t *,int );");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_pool_size_set. Expected uri_t.");
        XSRETURN(1);
    }
    _arg1 = (int )SvIV(ST(1));
    _result = (int )uri_pool_size_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

#define uri_pool_size_get(_swigobj) ((int ) _swigobj->pool_size)
XS(_wrap_uri_t_pool_size_get) {

    int  _result;
    uri_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: uri_t_pool_size_get(uri_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_pool_size_get. Expected uri_t.");
        XSRETURN(1);
    }
    _result = (int )uri_pool_size_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

static char * uri_furi_set(uri_t *obj, char *val) {
    if (obj->furi) free(obj->furi);
    obj->furi = (char *) malloc(strlen(val)+1);
    strcpy(obj->furi,val);
    return val;
}
XS(_wrap_uri_t_furi_set) {

    char * _result;
    uri_t * _arg0;
    char * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: uri_t_furi_set(uri_t *,char *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_furi_set. Expected uri_t.");
        XSRETURN(1);
    }
    _arg1 = (char *) SvPV(ST(1),na);
    _result = (char *)uri_furi_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define uri_furi_get(_swigobj) ((char *) _swigobj->furi)
XS(_wrap_uri_t_furi_get) {

    char * _result;
    uri_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: uri_t_furi_get(uri_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_furi_get. Expected uri_t.");
        XSRETURN(1);
    }
    _result = (char *)uri_furi_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define uri_furi_size_set(_swigobj,_swigval) (_swigobj->furi_size = _swigval,_swigval)
XS(_wrap_uri_t_furi_size_set) {

    int  _result;
    uri_t * _arg0;
    int  _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: uri_t_furi_size_set(uri_t *,int );");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_furi_size_set. Expected uri_t.");
        XSRETURN(1);
    }
    _arg1 = (int )SvIV(ST(1));
    _result = (int )uri_furi_size_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

#define uri_furi_size_get(_swigobj) ((int ) _swigobj->furi_size)
XS(_wrap_uri_t_furi_size_get) {

    int  _result;
    uri_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: uri_t_furi_size_get(uri_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_furi_size_get. Expected uri_t.");
        XSRETURN(1);
    }
    _result = (int )uri_furi_size_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

static char * uri_uri_set(uri_t *obj, char *val) {
    if (obj->uri) free(obj->uri);
    obj->uri = (char *) malloc(strlen(val)+1);
    strcpy(obj->uri,val);
    return val;
}
XS(_wrap_uri_t_uri_set) {

    char * _result;
    uri_t * _arg0;
    char * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: uri_t_uri_set(uri_t *,char *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_uri_set. Expected uri_t.");
        XSRETURN(1);
    }
    _arg1 = (char *) SvPV(ST(1),na);
    _result = (char *)uri_uri_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define uri_uri_get(_swigobj) ((char *) _swigobj->uri)
XS(_wrap_uri_t_uri_get) {

    char * _result;
    uri_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: uri_t_uri_get(uri_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_uri_get. Expected uri_t.");
        XSRETURN(1);
    }
    _result = (char *)uri_uri_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define uri_uri_size_set(_swigobj,_swigval) (_swigobj->uri_size = _swigval,_swigval)
XS(_wrap_uri_t_uri_size_set) {

    int  _result;
    uri_t * _arg0;
    int  _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: uri_t_uri_size_set(uri_t *,int );");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_uri_size_set. Expected uri_t.");
        XSRETURN(1);
    }
    _arg1 = (int )SvIV(ST(1));
    _result = (int )uri_uri_size_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

#define uri_uri_size_get(_swigobj) ((int ) _swigobj->uri_size)
XS(_wrap_uri_t_uri_size_get) {

    int  _result;
    uri_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: uri_t_uri_size_get(uri_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_uri_size_get. Expected uri_t.");
        XSRETURN(1);
    }
    _result = (int )uri_uri_size_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

static char * uri_robots_set(uri_t *obj, char *val) {
    if (obj->robots) free(obj->robots);
    obj->robots = (char *) malloc(strlen(val)+1);
    strcpy(obj->robots,val);
    return val;
}
XS(_wrap_uri_t_robots_set) {

    char * _result;
    uri_t * _arg0;
    char * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: uri_t_robots_set(uri_t *,char *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_robots_set. Expected uri_t.");
        XSRETURN(1);
    }
    _arg1 = (char *) SvPV(ST(1),na);
    _result = (char *)uri_robots_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define uri_robots_get(_swigobj) ((char *) _swigobj->robots)
XS(_wrap_uri_t_robots_get) {

    char * _result;
    uri_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: uri_t_robots_get(uri_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_robots_get. Expected uri_t.");
        XSRETURN(1);
    }
    _result = (char *)uri_robots_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define uri_robots_size_set(_swigobj,_swigval) (_swigobj->robots_size = _swigval,_swigval)
XS(_wrap_uri_t_robots_size_set) {

    int  _result;
    uri_t * _arg0;
    int  _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: uri_t_robots_size_set(uri_t *,int );");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_robots_size_set. Expected uri_t.");
        XSRETURN(1);
    }
    _arg1 = (int )SvIV(ST(1));
    _result = (int )uri_robots_size_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

#define uri_robots_size_get(_swigobj) ((int ) _swigobj->robots_size)
XS(_wrap_uri_t_robots_size_get) {

    int  _result;
    uri_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: uri_t_robots_size_get(uri_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_robots_size_get. Expected uri_t.");
        XSRETURN(1);
    }
    _result = (int )uri_robots_size_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

#define uri_desc_set(_swigobj,_swigval) (_swigobj->desc = _swigval,_swigval)
XS(_wrap_uri_t_desc_set) {

    struct uri_scheme_desc * _result;
    uri_t * _arg0;
    struct uri_scheme_desc * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: uri_t_desc_set(uri_t *,struct uri_scheme_desc *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_desc_set. Expected uri_t.");
        XSRETURN(1);
    }
    if (SWIG_GetPtr(ST(1),(void **) &_arg1,"uri_scheme_desc")) {
        croak("Type error in argument 2 of uri_t_desc_set. Expected uri_scheme_desc.");
        XSRETURN(1);
    }
    _result = (struct uri_scheme_desc *)uri_desc_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setref_pv(ST(argvi++),"uri_scheme_desc", (void *) _result);
    XSRETURN(argvi);
}

#define uri_desc_get(_swigobj) ((struct uri_scheme_desc *) _swigobj->desc)
XS(_wrap_uri_t_desc_get) {

    struct uri_scheme_desc * _result;
    uri_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: uri_t_desc_get(uri_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"uri_t")) {
        croak("Type error in argument 1 of uri_t_desc_get. Expected uri_t.");
        XSRETURN(1);
    }
    _result = (struct uri_scheme_desc *)uri_desc_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setref_pv(ST(argvi++),"uri_scheme_desc", (void *) _result);
    XSRETURN(argvi);
}

XS(_wrap_perl5_uri_var_init) {
    dXSARGS;
    SV *sv;
    cv = cv; items = items;
    swig_setiv("URI_MODE_CANNONICAL", (long) 0x01);
    swig_setiv("URI_MODE_ERROR_STDERR", (long) 0x02);
    swig_setiv("URI_MODE_FLAG_DEFAULT", (long) ((0x01)|(0x02)));
    swig_setiv("URI_INFO_CANNONICAL", (long) 0x0001);
    swig_setiv("URI_INFO_URI", (long) 0x0002);
    swig_setiv("URI_INFO_FURI", (long) 0x0004);
    swig_setiv("URI_INFO_RELATIVE", (long) 0x0008);
    swig_setiv("URI_INFO_RELATIVE_PATH", (long) 0x0010);
    swig_setiv("URI_INFO_EMPTY", (long) 0x0020);
    swig_setiv("URI_INFO_PARSED", (long) 0x0040);
    swig_setiv("URI_INFO_FILE", (long) 0x0200);
    swig_setiv("URI_INFO_ROBOTS", (long) 0x0400);
    swig_setiv("URI_FURI_REAL_PATH", (long) 1);
    swig_setiv("URI_FURI_NOP", (long) 0);
    swig_setiv("URI_STRING_FURI_STYLE", (long) 0x01);
    swig_setiv("URI_STRING_URI_STYLE", (long) 0x02);
    swig_setiv("URI_STRING_ROBOTS_STYLE", (long) 0x04);
    swig_setiv("URI_STRING_URI_NOHASH_STYLE", (long) 0x08);
    sv = perl_get_sv("uri_errstr",TRUE | 0x2);
    swig_create_magic(sv,"uri_errstr", MAGIC_CAST MAGIC_CLASS _wrap_set_uri_errstr, MAGIC_CAST MAGIC_CLASS _wrap_val_uri_errstr);
    swig_setiv("URI_NOT_CANNONICAL", (long) -1);
    swig_setiv("URI_CANNONICAL", (long) 0);
    swig_setiv("URI_CANNONICALIZE_TEST", (long) 0x01);
    swig_setiv("URI_CANNONICALIZE_TRANSFORM", (long) 0x02);
    XSRETURN(1);
}
#ifdef __cplusplus
extern "C"
#endif
XS(boot_uri) {
	 dXSARGS;
	 char *file = __FILE__;
	 cv = cv; items = items;
	 newXS("uric::var_uri_init", _wrap_perl5_uri_var_init, file);
	 newXS("uric::uri_mode", _wrap_uri_mode, file);
	 newXS("uric::uri_modep", _wrap_uri_modep, file);
	 newXS("uric::uri_alloc", _wrap_uri_alloc, file);
	 newXS("uric::uri_realloc", _wrap_uri_realloc, file);
	 newXS("uric::uri_free", _wrap_uri_free, file);
	 newXS("uric::uri_abs", _wrap_uri_abs, file);
	 newXS("uric::uri_abs_1", _wrap_uri_abs_1, file);
	 newXS("uric::uri_port", _wrap_uri_port, file);
	 newXS("uric::uri_netloc", _wrap_uri_netloc, file);
	 newXS("uric::uri_auth", _wrap_uri_auth, file);
	 newXS("uric::uri_all_path", _wrap_uri_all_path, file);
	 newXS("uric::uri_copy", _wrap_uri_copy, file);
	 newXS("uric::uri_dump", _wrap_uri_dump, file);
	 newXS("uric::uri_furi", _wrap_uri_furi, file);
	 newXS("uric::uri_uri", _wrap_uri_uri, file);
	 newXS("uric::uri_robots", _wrap_uri_robots, file);
	 newXS("uric::uri2object", _wrap_uri2object, file);
	 newXS("uric::uri_furi_string", _wrap_uri_furi_string, file);
	 newXS("uric::uri_cannonicalize_string", _wrap_uri_cannonicalize_string, file);
	 newXS("uric::uri_cannonicalize", _wrap_uri_cannonicalize, file);
	 newXS("uric::uri_parse", _wrap_uri_parse, file);
	 newXS("uric::uri_t_info_set", _wrap_uri_t_info_set, file);
	 newXS("uric::uri_t_info_get", _wrap_uri_t_info_get, file);
	 newXS("uric::uri_t_scheme_set", _wrap_uri_t_scheme_set, file);
	 newXS("uric::uri_t_scheme_get", _wrap_uri_t_scheme_get, file);
	 newXS("uric::uri_t_host_set", _wrap_uri_t_host_set, file);
	 newXS("uric::uri_t_host_get", _wrap_uri_t_host_get, file);
	 newXS("uric::uri_t_port_set", _wrap_uri_t_port_set, file);
	 newXS("uric::uri_t_port_get", _wrap_uri_t_port_get, file);
	 newXS("uric::uri_t_path_set", _wrap_uri_t_path_set, file);
	 newXS("uric::uri_t_path_get", _wrap_uri_t_path_get, file);
	 newXS("uric::uri_t_params_set", _wrap_uri_t_params_set, file);
	 newXS("uric::uri_t_params_get", _wrap_uri_t_params_get, file);
	 newXS("uric::uri_t_query_set", _wrap_uri_t_query_set, file);
	 newXS("uric::uri_t_query_get", _wrap_uri_t_query_get, file);
	 newXS("uric::uri_t_frag_set", _wrap_uri_t_frag_set, file);
	 newXS("uric::uri_t_frag_get", _wrap_uri_t_frag_get, file);
	 newXS("uric::uri_t_user_set", _wrap_uri_t_user_set, file);
	 newXS("uric::uri_t_user_get", _wrap_uri_t_user_get, file);
	 newXS("uric::uri_t_passwd_set", _wrap_uri_t_passwd_set, file);
	 newXS("uric::uri_t_passwd_get", _wrap_uri_t_passwd_get, file);
	 newXS("uric::uri_t_pool_set", _wrap_uri_t_pool_set, file);
	 newXS("uric::uri_t_pool_get", _wrap_uri_t_pool_get, file);
	 newXS("uric::uri_t_pool_size_set", _wrap_uri_t_pool_size_set, file);
	 newXS("uric::uri_t_pool_size_get", _wrap_uri_t_pool_size_get, file);
	 newXS("uric::uri_t_furi_set", _wrap_uri_t_furi_set, file);
	 newXS("uric::uri_t_furi_get", _wrap_uri_t_furi_get, file);
	 newXS("uric::uri_t_furi_size_set", _wrap_uri_t_furi_size_set, file);
	 newXS("uric::uri_t_furi_size_get", _wrap_uri_t_furi_size_get, file);
	 newXS("uric::uri_t_uri_set", _wrap_uri_t_uri_set, file);
	 newXS("uric::uri_t_uri_get", _wrap_uri_t_uri_get, file);
	 newXS("uric::uri_t_uri_size_set", _wrap_uri_t_uri_size_set, file);
	 newXS("uric::uri_t_uri_size_get", _wrap_uri_t_uri_size_get, file);
	 newXS("uric::uri_t_robots_set", _wrap_uri_t_robots_set, file);
	 newXS("uric::uri_t_robots_get", _wrap_uri_t_robots_get, file);
	 newXS("uric::uri_t_robots_size_set", _wrap_uri_t_robots_size_set, file);
	 newXS("uric::uri_t_robots_size_get", _wrap_uri_t_robots_size_get, file);
	 newXS("uric::uri_t_desc_set", _wrap_uri_t_desc_set, file);
	 newXS("uric::uri_t_desc_get", _wrap_uri_t_desc_get, file);
/*
 * These are the pointer type-equivalency mappings. 
 * (Used by the SWIG pointer type-checker).
 */
	 SWIG_RegisterMapping("unsigned short","short",0);
	 SWIG_RegisterMapping("uri","uri_t",0);
	 SWIG_RegisterMapping("uri","struct uri",0);
	 SWIG_RegisterMapping("long","unsigned long",0);
	 SWIG_RegisterMapping("long","signed long",0);
	 SWIG_RegisterMapping("signed short","short",0);
	 SWIG_RegisterMapping("signed int","int",0);
	 SWIG_RegisterMapping("short","unsigned short",0);
	 SWIG_RegisterMapping("short","signed short",0);
	 SWIG_RegisterMapping("unsigned long","long",0);
	 SWIG_RegisterMapping("uri_t","struct uri",0);
	 SWIG_RegisterMapping("uri_t","uri",0);
	 SWIG_RegisterMapping("int","unsigned int",0);
	 SWIG_RegisterMapping("int","signed int",0);
	 SWIG_RegisterMapping("unsigned int","int",0);
	 SWIG_RegisterMapping("struct uri","uri_t",0);
	 SWIG_RegisterMapping("struct uri","uri",0);
	 SWIG_RegisterMapping("signed long","long",0);
	 ST(0) = &sv_yes;
	 XSRETURN(1);
}
